# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-controller-manager
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel
    control-plane: redis-controller-manager
spec:
  selector:
    matchLabels: &labels
      control-plane: redis-controller-manager
  serviceName: redis-controller-manager
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: redis-controller-manager
      containers:
      - image: ko://knative.dev/eventing-redis/source/cmd/controller
        name: manager
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: knative.dev/sources
        - name: CONFIG_LEADERELECTION_NAME
          value: config-leader-election-redis
        - name: STREAMSOURCE_RA_IMAGE
          value: ko://knative.dev/eventing-redis/source/cmd/receive_adapter
        - name: CONFIG_REDIS_NUMCONSUMERS
          value: config-redis-numconsumers     
      terminationGracePeriodSeconds: 10

